bug/ICS-204 domains not cached
energywebfoundation/ew-credentials pull request #18
Opened 2022-05-16 07:18 UTC by JGiter

Domains will be read from RoleResolverV2 as we not using PublicResolver any more. Or may be configure this depending on chain?

2022-05-16 07:26 UTC, Harasz approved these changes

2022-05-16 12:13 UTC, jrhender requested changes
I don't think this change is necessary.

2022-05-16 12:23 UTC, jrhender commented
`getSubdomainsUsingResolver` will use all of the configured resolvers from the logs of the `domainNotifier` contract https://github.com/energywebfoundation/ew-credentials/blob/fdd462e011f182a04b0116b79f05fd6984b8b64e/packages/credential-governance/src/domain-hierarchy.ts#L107
The public resolver is optional.  https://github.com/energywebfoundation/ew-credentials/blob/fdd462e011f182a04b0116b79f05fd6984b8b64e/packages/credential-governance/src/domain-hierarchy.ts#L70
I don't see the value in removing backwards compatibility at this stage, other than cleaning up the code. If this is done, it should be done very intentionally and carefully.

2022-05-18 06:13 UTC, JGiter commented
Closed as risk of break existing code is still high

2022-05-18 06:13 UTC, closed without merging